### ISSUE TITLE
좋아요, 싫어요 버튼 버그 

### ISSUE THREAD

**Issue by arin-kwak** [ReallyView/mobile-client-v2#26]
Main 에서 사진을 클릭하여 리뷰 창으로 바로 이동하면 좋아요, 싫어요가 이상하게 동작합니다.
![img_0148 2](https://user-images.githubusercontent.com/29162801/48310248-1bab4400-e5cf-11e8-802b-e2b6a68659e9.PNG)
![img_0149](https://user-images.githubusercontent.com/29162801/48310246-1a7a1700-e5cf-11e8-86f7-fbbe1698aa0b.PNG)

**Comment by arin-kwak** [comment]
자신이 좋아요, 싫어요를 기존에 한 리뷰인지 검사가 안되는 것으로 예상됩니다.

**Comment by sskim0126** [comment]
해결했습니다.
